<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => '积分商城',
  'url' => 'https://market.minilott.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class="footer" style="text-align:center"><p class="links"><a href="">关于我们</a>|<a href="">常见问题</a>|<a href="">安全交易</a>|<a href="">购买流程</a>|<a href="">如何付款</a>|<a href="">联系我们</a>|<a href="">合作提案</a></p><p class="copyright">Powered by <a href="http://www.aircheng.com">iWebShop</a></p>Copyright © 2005-2014 <a class="copyys" target="_blank" href="http://www.miibeian.gov.cn/">鲁ICP备01000010号</a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => '积分商城',
  'index_seo_keywords' => '积分商城',
  'index_seo_description' => '积分商城',
  'goods_no_pre' => 'SD',
  'commission' => '',
  'store_num_warning' => '1',
  'reg_option' => '3',
  'api_url' => 'http://localhost:8081/',
  'key' => 'b0944e407ae1a5ebc2229a22dee75c94',
  'sms_platform' => 'aoyihutong',
  'sms_userid' => '8120',
  'sms_username' => 'lingcai1',
  'sms_pwd' => '!y?qeo$&amp;m$',
  'logo' => 'upload/logo/20190909034851627.png',
)?>
